"""
Advanced Python - 39: Poetry
============================
Topics: pyproject.toml under Poetry 2.x; [project] vs [tool.poetry]; constraint
        expansion (^, ~, *, ~=, exact, ranges); dependency groups vs extras; the
        install flag surface; poetry.lock anatomy and content-hash freshness;
        lock-satisfies-manifest; private sources and priorities; package-mode;
        poetry, uv, pip-tools.

Why this matters for AI/backend engineering:
    An eval run that drifts because NumPy moved is not a bug report, it is an
    unreproducible experiment. Poetry resolves once, pins every transitive
    version plus file hashes in poetry.lock, and every machine installs that
    graph. This file exercises the parts you can run offline with the standard
    library: parse the manifest, expand a constraint, decide which groups
    install, and prove a lockfile is fresh against its manifest.

Run:      python 39-poetry.py
Verify:   python 39-poetry.py --verify
Reference: https://python-poetry.org/docs/
           https://python-poetry.org/docs/pyproject/
           https://python-poetry.org/docs/dependency-specification/
"""

from __future__ import annotations

import copy
import hashlib
import json
import sys

import tomllib  # type: ignore[import-not-found]

# --------------------------------------------------------------------------- #
# Section 1: pyproject.toml anatomy (Poetry 2.x)
# --------------------------------------------------------------------------- #
# Two metadata tables can coexist:
#   [project]            - PEP 621 standard. Since Poetry 2.4 this is the
#                          default output of `poetry new` / `poetry init`.
#                          Constraint syntax here is PEP 508 only: a bare
#                          "1.2.3" means EXACT, and ^ / ~ are NOT allowed.
#   [tool.poetry.*]      - Poetry-native syntax, still fully supported and the
#                          only place for ^ / ~, dependency groups, sources,
#                          package-mode, requires-poetry.
# Poetry warns when the same dependency is declared in both.
EXAMPLE_PYPROJECT = """
[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "rag-utils"
version = "1.2.0"
description = "Shared retrieval helpers for the RAG services"
requires-python = ">=3.10"
dependencies = [
    "numpy (>=1.26,<3.0.0)",
    "pydantic (>=2.5,<3.0.0)",
]

[project.optional-dependencies]
qdrant = ["qdrant-client (>=1.9,<2.0.0)"]

[project.scripts]
rag-index = "rag_utils.cli:main"

[tool.poetry]
package-mode = true
requires-poetry = ">=2.0"

[tool.poetry.group.dev]
# Not marked optional -> installed by default by `poetry install`.
[tool.poetry.group.dev.dependencies]
pytest = ">=8.0"

[dependency-groups]
# PEP 735 group. Poetry reads it; combine with [tool.poetry.group.<name>]
# below to mark it optional.
lint = ["mypy (>=1.11,<2.0.0)"]

[tool.poetry.group.lint]
optional = true

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.ruff]
line-length = 100
"""

# A trimmed poetry.lock. Real locks also carry per-file hashes; those are
# elided here because nothing in this exercise reads them.
EXAMPLE_LOCK = """
# This file is automatically @generated by Poetry 2.5.0 and should not be
# changed by hand.

[[package]]
name = "numpy"
version = "1.26.4"
description = "NumPy is the fundamental package for scientific computing with Python."
optional = false
python-versions = ">=3.9"
files = [
    {file = "numpy-1.26.4-cp312-cp312-win_amd64.whl", hash = "sha256:00000000"},
]

[[package]]
name = "pydantic"
version = "2.9.2"
description = "Data validation using Python type hints."
optional = false
python-versions = ">=3.8"
files = [
    {file = "pydantic-2.9.2-py3-none-any.whl", hash = "sha256:00000000"},
]

[[package]]
name = "qdrant-client"
version = "1.12.1"
description = "Client library for the Qdrant vector similarity search engine."
optional = false
python-versions = ">=3.8"
files = [
    {file = "qdrant_client-1.12.1-py3-none-any.whl", hash = "sha256:00000000"},
]

[[package]]
name = "pytest"
version = "8.3.4"
description = "pytest: simple powerful testing with Python"
optional = false
python-versions = ">=3.8"
files = [
    {file = "pytest-8.3.4-py3-none-any.whl", hash = "sha256:00000000"},
]

[[package]]
name = "mypy"
version = "1.11.2"
description = "Optional static typing for Python"
optional = false
python-versions = ">=3.8"
files = [
    {file = "mypy-1.11.2-cp312-cp312-win_amd64.whl", hash = "sha256:00000000"},
]

[metadata]
lock-version = "2.1"
python-versions = ">=3.10"
content-hash = "cfba36c46b1c2e60c52eb7e78020b716afac44b248104076a565427628188bdb"
"""


def load_pyproject() -> dict:
    """Parse the example manifest with the stdlib TOML parser (3.11+)."""
    parsed: dict = tomllib.loads(EXAMPLE_PYPROJECT)
    return parsed


def load_lock() -> dict:
    """Parse the example lockfile."""
    parsed: dict = tomllib.loads(EXAMPLE_LOCK)
    return parsed


def classify_manifest(data: dict) -> dict:
    """Report which metadata tables a pyproject.toml uses and where it clashes."""
    project = data.get("project", {})
    poetry = data.get("tool", {}).get("poetry", {})
    pep621_deps = list(project.get("dependencies", []))
    poetry_deps = set(poetry.get("dependencies", {}))
    pep621_names = {parse_requirement(d)[0].lower() for d in pep621_deps}
    return {
        "uses_pep621": bool(project),
        "uses_poetry_table": bool(poetry),
        "pep621_deps": pep621_deps,
        "poetry_groups": sorted(poetry.get("group", {})),
        "pep735_groups": sorted(data.get("dependency-groups", {})),
        "dupes": sorted(pep621_names & {n.lower() for n in poetry_deps}),
    }


# --------------------------------------------------------------------------- #
# Section 2: constraint expansion
# --------------------------------------------------------------------------- #
# Poetry constraint syntax (tool.poetry tables) vs PEP 508 (project table).
#   ^1.2.3 -> >=1.2.3,<2.0.0   (caret: leftmost non-zero digit may not bump)
#   ~1.2.3 -> >=1.2.3,<1.3.0   (tilde: only patch may bump)
#   1.2.3  -> ==1.2.3          (bare version is EXACT, not caret)
#   1.2.*  -> >=1.2.0,<1.3.0   (wildcard)
#   ~=1.2.3-> >=1.2.3,<1.3.0   (PEP 440 compatible release)
_OPERATORS = ("===", "==", "!=", ">=", "<=", "~=", ">", "<")


def _split_op(clause: str) -> tuple[str, str]:
    """Split '<operator><version>' into (operator, version)."""
    text = clause.strip()
    for op in _OPERATORS:
        if text.startswith(op):
            return op, text[len(op) :].strip()
    return "", text


def _nums(version: str) -> list[int]:
    """Parse the numeric prefix of a version into ints ('' parts skipped)."""
    core = ""
    for ch in version.strip():
        if ch.isdigit() or ch == ".":
            core += ch
        else:
            break
    return [int(p) for p in core.split(".") if p]


def _pad(parts: list[int], width: int = 3) -> list[int]:
    """Pad a version component list with zeros up to `width`."""
    return parts + [0] * (width - len(parts))


def _caret(version: str) -> tuple[str, str]:
    """^1.2.3 -> >=1.2.3,<2.0.0 ; ^0.2.3 -> >=0.2.3,<0.3.0 ; ^0 -> >=0.0.0,<1.0.0."""
    parts = _nums(version)
    if not parts:
        raise ValueError(f"bad caret constraint: ^{version}")
    low = ".".join(str(p) for p in _pad(parts))
    if parts[0] > 0:
        high = f"{parts[0] + 1}.0.0"
    elif len(parts) == 1:
        high = "1.0.0"
    elif len(parts) == 2:
        high = f"0.{parts[1] + 1}.0" if parts[1] > 0 else "0.1.0"
    elif parts[1] > 0:
        high = f"0.{parts[1] + 1}.0"
    elif parts[2] > 0:
        high = f"0.0.{parts[2] + 1}"
    else:
        high = "0.0.1"
    return (f">={low}", f"<{high}")


def _tilde(version: str) -> tuple[str, str]:
    """~1.2.3 -> >=1.2.3,<1.3.0 ; ~1.2 -> >=1.2.0,<1.3.0 ; ~1 -> >=1.0.0,<2.0.0."""
    parts = _nums(version)
    if not parts:
        raise ValueError(f"bad tilde constraint: ~{version}")
    low = ".".join(str(p) for p in _pad(parts))
    if len(parts) == 1:
        high = f"{parts[0] + 1}.0.0"
    else:
        high = f"{parts[0]}.{parts[1] + 1}.0"
    return (f">={low}", f"<{high}")


def _compatible(version: str) -> tuple[str, str]:
    """~=1.2.3 -> >=1.2.3,<1.3.0 ; ~=1.2 -> >=1.2.0,<2.0.0 (PEP 440)."""
    parts = _nums(version)
    if len(parts) < 2:
        raise ValueError(f"~= needs at least two components: ~= {version}")
    low = ".".join(str(p) for p in _pad(parts))
    if len(parts) == 2:
        high = f"{parts[0] + 1}.0.0"
    else:
        high = f"{parts[0]}.{parts[1] + 1}.0"
    return (f">={low}", f"<{high}")


def _wildcard(spec: str) -> tuple[str, str]:
    """'*' -> >=0.0.0 ; '1.*' -> >=1.0.0,<2.0.0 ; '1.2.*' -> >=1.2.0,<1.3.0."""
    base = spec.split("*")[0].strip().rstrip(".")
    parts = _nums(base) if base else []
    if not parts:
        return (">=0.0.0", "")
    low = ".".join(str(p) for p in _pad(parts))
    if len(parts) == 1:
        return (f">={low}", f"<{parts[0] + 1}.0.0")
    return (f">={low}", f"<{parts[0]}.{parts[1] + 1}.0")


def expand_constraint(spec: str) -> tuple[str, str]:
    """Expand a constraint into a (lower, upper) pair of PEP 508 specifiers.

    An empty string means 'unbounded on that side'. Raises on operators the
    teaching expander does not model (!=, ===).
    """
    text = spec.strip()
    if not text:
        return ("", "")
    if text.startswith("^"):
        return _caret(text[1:])
    if text.startswith("~="):
        return _compatible(text[2:])
    if text.startswith("~"):
        return _tilde(text[1:])
    if "*" in text:
        return _wildcard(text)
    if "," in text:
        lower, upper = "", ""
        for clause in (c.strip() for c in text.split(",")):
            op, version = _split_op(clause)
            if op in (">=", ">"):
                lower = f"{op}{version}"
            elif op in ("<", "<="):
                upper = f"{op}{version}"
            elif op == "==":
                lower = clause
            else:
                raise ValueError(f"unsupported clause in range: {clause!r}")
        return (lower, upper)
    op, version = _split_op(text)
    if op == "" or op == "==":
        return (f"=={version}", "")
    if op in (">=", ">"):
        return (f"{op}{version}", "")
    if op in ("<", "<="):
        return ("", f"{op}{version}")
    raise ValueError(f"unsupported constraint: {spec!r}")


def _vkey(version: str) -> tuple[int, ...]:
    """Comparable 4-tuple for a version string (prerelease suffixes dropped)."""
    return tuple(_pad(_nums(version), 4))


def version_in_bounds(version: str, bounds: tuple[str, str]) -> bool:
    """True when `version` satisfies the (lower, upper) pair."""
    lower, upper = bounds
    value = _vkey(version)
    if lower:
        op, bound = _split_op(lower)
        target = _vkey(bound)
        if op == "==":
            if value != target:
                return False
        elif op == ">=":
            if not value >= target:
                return False
        elif op == ">":
            if not value > target:
                return False
        else:
            raise ValueError(f"unsupported lower bound: {lower}")
    if upper:
        op, bound = _split_op(upper)
        target = _vkey(bound)
        if op == "<":
            if not value < target:
                return False
        elif op == "<=":
            if not value <= target:
                return False
        else:
            raise ValueError(f"unsupported upper bound: {upper}")
    return True


def parse_requirement(req: str) -> tuple[str, str, str]:
    """Split a PEP 508 requirement into (name, extras, specifier).

    Accepts both 'numpy (>=1.26,<3)' and 'numpy>=1.26,<3'.
    """
    text = req.strip()
    head, paren, rest = text.partition("(")
    if paren:
        spec = rest.rstrip(")").strip()
    else:
        spec = ""
        for i, ch in enumerate(text):
            if ch in "<>!=~@":
                head, spec = text[:i], text[i:]
                break
    extras = ""
    if "[" in head:
        name_part, _, tail = head.partition("[")
        extras = tail.strip().rstrip("]").strip()
        head = name_part
    return (head.strip(), extras, spec.strip())


# --------------------------------------------------------------------------- #
# Section 3: dependency groups vs extras, and the install flag surface
# --------------------------------------------------------------------------- #
# extras      = shipped inside the package; install with `-E name` / `--all-extras`
# groups      = development-only dependency sets; never shipped
# --with      = add an optional group
# --without   = drop a non-optional group
# --only      = install exactly these groups (overrides --with/--without)
# --all-groups= every declared group
def groups_to_install(
    groups: dict[str, bool],
    only: list[str] | None = None,
    with_groups: list[str] | None = None,
    without: list[str] | None = None,
) -> list[str]:
    """Resolve the set of groups Poetry would install for a flag combination.

    `groups` maps group name -> is_optional. 'main' (the shipped runtime deps)
    is always present and non-optional.
    """
    only = only or []
    with_groups = with_groups or []
    drop = set(without or [])
    known = set(groups)
    if only:
        selected = set(only)
    else:
        selected = {g for g, optional in groups.items() if not optional}
        selected.update(with_groups)
    unknown = (selected | drop | set(with_groups)) - known
    if unknown:
        raise ValueError(f"unknown group(s): {sorted(unknown)}")
    if only:
        return sorted(selected)
    return sorted(selected - drop)


# --------------------------------------------------------------------------- #
# Section 4: poetry.lock content-hash freshness
# --------------------------------------------------------------------------- #
# Locker.py hashes a *subset* of pyproject.toml: the manifest fields that can
# change resolution (dependencies, requires-python, sources, groups) and NOT
# unrelated tables such as [tool.ruff]. `poetry check --lock` compares this
# hash with the one stored under [metadata] in poetry.lock.
RELEVANT_PROJECT_KEYS = (
    "name",
    "version",
    "description",
    "requires-python",
    "dependencies",
    "optional-dependencies",
)
RELEVANT_POETRY_KEYS = (
    "dependencies",
    "source",
    "extras",
    "dev-dependencies",
    "group",
)


def content_hash(data: dict) -> str:
    """Mirror of Poetry's Locker content hash over the relevant manifest keys."""
    project = data.get("project", {})
    groups = data.get("dependency-groups", {})
    poetry = data.get("tool", {}).get("poetry", {})

    rel_project = {k: project[k] for k in RELEVANT_PROJECT_KEYS if k in project}
    rel_groups = dict(groups)
    rel_poetry = {k: poetry[k] for k in RELEVANT_POETRY_KEYS if k in poetry}

    relevant: dict = {}
    if rel_project:
        relevant["project"] = rel_project
    if rel_groups:
        relevant["dependency-groups"] = rel_groups
    if relevant:
        relevant["tool"] = {"poetry": rel_poetry}
    else:
        relevant = rel_poetry

    payload = json.dumps(relevant, sort_keys=True).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def lock_is_fresh(pyproject: dict, lock: dict) -> bool:
    """True when poetry.lock was generated from exactly this manifest."""
    stored = lock.get("metadata", {}).get("content-hash")
    return stored is not None and stored == content_hash(pyproject)


# --------------------------------------------------------------------------- #
# Section 5: does the lockfile satisfy the manifest?
# --------------------------------------------------------------------------- #
def unsatisfied_dependencies(pyproject: dict, lock: dict) -> list[str]:
    """Direct requirements the locked versions do not satisfy, sorted."""
    locked = {p["name"].lower(): p["version"] for p in lock.get("package", [])}
    problems: list[str] = []

    def check(name: str, spec: str) -> None:
        bounds = expand_constraint(spec)
        version = locked.get(name.lower())
        if version is None:
            problems.append(f"{name}: missing from poetry.lock")
        elif not version_in_bounds(version, bounds):
            problems.append(f"{name}: {version} outside {spec}")

    for req in pyproject.get("project", {}).get("dependencies", []):
        name, _, spec = parse_requirement(req)
        check(name, spec)
    for extra_deps in pyproject.get("project", {}).get("optional-dependencies", {}).values():
        for req in extra_deps:
            name, _, spec = parse_requirement(req)
            check(name, spec)
    poetry = pyproject.get("tool", {}).get("poetry", {})
    for group in poetry.get("group", {}).values():
        for name, constraint in group.get("dependencies", {}).items():
            spec = constraint if isinstance(constraint, str) else str(constraint.get("version", ""))
            check(name, spec)
    for reqs in pyproject.get("dependency-groups", {}).values():
        for req in reqs:
            name, _, spec = parse_requirement(req)
            check(name, spec)
    return sorted(problems)


# --------------------------------------------------------------------------- #
# Section 6: sources and priorities
# --------------------------------------------------------------------------- #
_SOURCE_PRIORITIES = {"primary", "supplemental", "explicit", "legacy"}


def source_problems(data: dict) -> list[str]:
    """Validate [[tool.poetry.source]] entries and dependency source references."""
    problems: list[str] = []
    poetry = data.get("tool", {}).get("poetry", {})
    sources = poetry.get("source", [])
    names: list[str] = []
    for src in sources:
        name = src.get("name", "")
        if not name:
            problems.append("source without a name")
            continue
        if name in names:
            problems.append(f"duplicate source name: {name}")
        names.append(name)
        priority = src.get("priority")
        if priority not in _SOURCE_PRIORITIES:
            problems.append(f"bad priority on {name}: {priority}")
    for dep, spec in poetry.get("dependencies", {}).items():
        if isinstance(spec, dict) and spec.get("source") and spec["source"] not in names:
            problems.append(f"{dep}: unknown source {spec['source']}")
    return sorted(problems)


# --------------------------------------------------------------------------- #
# Section 7: the command surface (print-only)
# --------------------------------------------------------------------------- #
COMMAND_MAP = {
    "poetry new NAME / poetry init": "scaffold a project (PEP 621 by default)",
    "poetry add pkg": "add + resolve + lock + install",
    "poetry add --group dev pkg": "add into a named dependency group",
    "poetry remove pkg": "drop the dependency and relock",
    "poetry install": "install the locked graph into the venv",
    "poetry sync": "install --with uninstalling anything not in the lock",
    "poetry update pkg": "re-resolve one package, rewrite the lock",
    "poetry lock --regenerate": "ignore the old lock and resolve from scratch",
    "poetry check --lock": "fail if poetry.lock is stale (content-hash)",
    "poetry run CMD": "run CMD inside the project venv",
    "poetry export -f requirements.txt": "needs poetry-plugin-export (not bundled)",
    "poetry shell": "needs poetry-plugin-shell (not bundled)",
    "poetry self add poetry-plugin-x": "install a Poetry plugin",
    "poetry config --local KEY value": "write poetry.toml next to pyproject.toml",
}


# --------------------------------------------------------------------------- #
# Section 8: common mistakes (reference)
# --------------------------------------------------------------------------- #
# 1. Assuming '^1.2.3' inside [project] dependencies means >=1.2.3,<2.0.0.
#    PEP 508 rejects it; use '>=1.2.3,<2.0.0'. Poetry converts on `poetry add`.
# 2. Assuming a bare '1.2.3' in [tool.poetry.dependencies] is a caret range.
#    It is exact. Use '^1.2.3' when you meant a range.
# 3. Editing poetry.lock by hand. It is generated; regenerate it.
# 4. Committing pyproject.toml while gitignoring poetry.lock. Every developer
#    and CI runner then resolves independently -> non-reproducible runs.
# 5. Forgetting `optional = true` on a group, then wondering why `poetry
#    install` pulls docs/mkdocs into every dev environment.
# 6. Expecting `poetry export` or `poetry shell` out of the box on Poetry 2+.
#    Both live in plugins now.
# 7. Using `package-mode = false` on a library you actually publish.
# 8. Expecting uv/poetry to speed anything up without a committed lockfile.
#    The speed comes from the pinned graph, not the tool.


def demo_manifest() -> None:
    report = classify_manifest(load_pyproject())
    print("Manifest tables:")
    print(f"  PEP 621 [project]      : {report['uses_pep621']}")
    print(f"  [tool.poetry]          : {report['uses_poetry_table']}")
    print(f"  [tool.poetry.group]    : {report['poetry_groups']}")
    print(f"  [dependency-groups]    : {report['pep735_groups']}")
    print(f"  duplicate declarations : {report['dupes'] or 'none'}")


def demo_constraints() -> None:
    print("\nConstraint expansion (Poetry syntax):")
    for spec in ["^1.2.3", "^0.2.3", "~1.2.3", "1.2.3", "1.2.*", "~=1.2", ">=1.26,<3.0.0"]:
        low, high = expand_constraint(spec)
        print(f"  {spec:<14} -> {low:<12} {high}")
    caret = expand_constraint("^0.2.3")
    pod = expand_constraint(">=1.26,<3.0.0")
    print("\nMembership:")
    print(f"  0.2.9 inside ^0.2.3     : {version_in_bounds('0.2.9', caret)}")
    print(f"  0.3.0 inside ^0.2.3     : {version_in_bounds('0.3.0', caret)}")
    print(f"  1.26.4 inside >=1.26,<3 : {version_in_bounds('1.26.4', pod)}")
    print(f"  3.0.0 inside >=1.26,<3  : {version_in_bounds('3.0.0', pod)}")


def demo_groups() -> None:
    groups = {"main": False, "dev": False, "lint": True, "docs": True}
    print("\nGroup selection:")
    print(f"  default                : {groups_to_install(groups)}")
    print(f"  --with docs            : {groups_to_install(groups, with_groups=['docs'])}")
    print(f"  --without lint         : {groups_to_install(groups, without=['lint'])}")
    print(f"  --only main            : {groups_to_install(groups, only=['main'])}")


def demo_freshness() -> None:
    pyproject = load_pyproject()
    lock = load_lock()
    stale = copy.deepcopy(pyproject)
    stale["project"]["dependencies"].append("httpx (>=0.27,<1.0.0)")
    print("\nLock freshness:")
    print(f"  untouched manifest : {lock_is_fresh(pyproject, lock)}")
    print(f"  added a dependency : {lock_is_fresh(stale, lock)}")
    tool_only = copy.deepcopy(pyproject)
    tool_only["tool"]["ruff"]["line-length"] = 88
    print(f"  changed [tool.ruff]: {lock_is_fresh(tool_only, lock)}")
    print(f"  unsatisfied deps   : {unsatisfied_dependencies(pyproject, lock) or 'none'}")


def demo_commands() -> None:
    print("\nCommand map:")
    for cmd, note in COMMAND_MAP.items():
        print(f"  {cmd:<48} {note}")


def _verify() -> None:
    """Self-check. Silent on failure-free completion when run with --verify."""
    # Constraint table, straight from the Poetry docs.
    assert expand_constraint("^1.2.3") == (">=1.2.3", "<2.0.0")
    assert expand_constraint("^1.2") == (">=1.2.0", "<2.0.0")
    assert expand_constraint("^1") == (">=1.0.0", "<2.0.0")
    assert expand_constraint("^0.2.3") == (">=0.2.3", "<0.3.0")
    assert expand_constraint("^0.0.3") == (">=0.0.3", "<0.0.4")
    assert expand_constraint("^0.0") == (">=0.0.0", "<0.1.0")
    assert expand_constraint("^0") == (">=0.0.0", "<1.0.0")
    assert expand_constraint("~1.2.3") == (">=1.2.3", "<1.3.0")
    assert expand_constraint("~1.2") == (">=1.2.0", "<1.3.0")
    assert expand_constraint("~1") == (">=1.0.0", "<2.0.0")
    assert expand_constraint("1.2.3") == ("==1.2.3", "")
    assert expand_constraint("*") == (">=0.0.0", "")
    assert expand_constraint("1.*") == (">=1.0.0", "<2.0.0")
    assert expand_constraint("1.2.*") == (">=1.2.0", "<1.3.0")
    assert expand_constraint("~=1.2.3") == (">=1.2.3", "<1.3.0")
    assert expand_constraint("~=1.2") == (">=1.2.0", "<2.0.0")
    assert expand_constraint(">=1.26,<3.0.0") == (">=1.26", "<3.0.0")

    # Membership.
    low, high = expand_constraint("^0.2.3")
    assert version_in_bounds("0.2.9", (low, high))
    assert not version_in_bounds("0.3.0", (low, high))
    assert version_in_bounds("1.26.4", (">=1.26", "<3.0.0"))
    assert not version_in_bounds("3.0.0", (">=1.26", "<3.0.0"))

    # Requirement parsing.
    assert parse_requirement("numpy (>=1.26,<3.0.0)") == ("numpy", "", ">=1.26,<3.0.0")
    assert parse_requirement("numpy>=1.26") == ("numpy", "", ">=1.26")
    assert parse_requirement("qdrant-client[async] (>=1.9)") == ("qdrant-client", "async", ">=1.9")

    # Groups.
    groups = {"main": False, "dev": False, "lint": True, "docs": True}
    assert groups_to_install(groups) == ["dev", "main"]
    assert groups_to_install(groups, with_groups=["docs"]) == ["dev", "docs", "main"]
    assert groups_to_install(groups, without=["lint", "dev"]) == ["main"]
    assert groups_to_install(groups, only=["main"]) == ["main"]
    try:
        groups_to_install(groups, with_groups=["nope"])
        raise AssertionError("unknown group must raise")
    except ValueError:
        pass

    # Manifest / lock agreement.
    pyproject = load_pyproject()
    lock = load_lock()
    assert lock["metadata"]["content-hash"] == content_hash(pyproject)
    assert lock_is_fresh(pyproject, lock)
    assert unsatisfied_dependencies(pyproject, lock) == []

    stale = copy.deepcopy(pyproject)
    stale["project"]["dependencies"].append("httpx (>=0.27,<1.0.0)")
    assert not lock_is_fresh(stale, lock)

    cosmetic = copy.deepcopy(pyproject)
    cosmetic["tool"]["ruff"]["line-length"] = 88
    assert lock_is_fresh(cosmetic, lock)

    # Adding a locked version outside the range must be reported.
    drifted = copy.deepcopy(lock)
    for pkg in drifted["package"]:
        if pkg["name"] == "numpy":
            pkg["version"] = "3.1.0"
    assert unsatisfied_dependencies(pyproject, drifted) == ["numpy: 3.1.0 outside >=1.26,<3.0.0"]

    # Sources.
    assert source_problems(pyproject) == []
    broken = copy.deepcopy(pyproject)
    broken["tool"]["poetry"]["source"][0]["priority"] = "fastest"
    assert source_problems(broken) == ["bad priority on pytorch-cpu: fastest"]
    no_source = copy.deepcopy(pyproject)
    del no_source["tool"]["poetry"]["source"]
    assert source_problems(no_source) == []

    print("\n[OK] 39-poetry: all checks passed")


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--verify":
        _verify()
    else:
        demo_manifest()
        demo_constraints()
        demo_groups()
        demo_freshness()
        demo_commands()
        _verify()
